- name: install depencies
  apt: 
    name: ['git','tree',"tcl","tk","expect"]
    state: present
    
- name: Set sysctl File Limits
  copy:
    src: ./files/50-fs.conf
    dest: /etc/sysctl.d

- name: Set Shell File Limits
  copy:
    src: ../files/91-nofiles.conf
    dest: /etc/security/limits.d

- name: Set gaia filehandle Limits
  copy:
    src: ../files/limits.conf
    dest: "/lib/systemd/system/{{item}}.service.d"
  notify: reload systemctl
  with_items:
    - gaiad
    - gaiacli